### ISSUE TITLE
Please drop RPMEPOCH support

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#79]
The current RPMEPOCH design is a leftover before ab2-port introduction.

When I designed the PKGEPOCH in ab2-port, it was intended to be a fully rpm-compliant epoch, so it was only a bash integer, without anything fancy like makepkg floats. Yes, no need for a separate epoch.

Additionally, using a separate EPOCH lead to inconsistent outputs from `pm_getver`, since RPM only knows about the epoch being written in the spec.

Solution: In pm.sh, `declare -n RPMEPOCH=PKGEPOCH`.

**Comment by Icenowy** [comment]
The tradition epoch that I said is: If you do not attach such an epoch, your package will be denied by rpm, and your system won't be LSB-complicant

- 发送自我的Sony Xperia™智能手机

---- Mingye Wang编写 ----

The current RPMEPOCH design is a leftover before ab2-port introduction.

When I designed the PKGEPOCH in ab2-port, it was intended to be a fully rpm-compliant epoch, so it was only a bash integer, without anything fancy like makepkg floats.

Additionally, using a separate EPOCH lead to inconsistent outputs from `pm_getver`, since RPM only knows about the epoch being written in the spec.

Solution: In pm.sh, `declare -n RPMEPOCH=PKGEPOCH`.

---
Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/autobuild3/issues/79

**Comment by MingcongBai** [comment]
Yes, and perl is the classic case in the discussion.
2015年12月17日 下午9:42，"Icenowy Zheng" <notifications@github.com>写道：

**Comment by Arthur2e5** [comment]
So just make a `declare -i PKGEPOCH` in pmlib.

**Comment by MingcongBai** [comment]
The problem is do we want the hacky bit that RPM requires to be found on
DPKG as well...
2015年12月17日 下午9:44，"Mingye Wang" <notifications@github.com>写道：

**Comment by Arthur2e5** [comment]
The problem is with a fscking inconsistent output from `pm_getver`, your dependency info generated is fscking bootstrap.

**Comment by Icenowy** [comment]
Here's a solution: add the global epoch
to rpm levels
- 发送自我的Sony Xperia™智能手机

---- Mingye Wang编写 ----

The problem is with a fscking inconsistent output from `pm_getver`, your dependency info generated is fscking bootstrap.

---

**Comment by MingcongBai** [comment]
Very true. But calm down. A unity on version payload is not a issue on
functionality anyways, I mean, I can live with an extra epoch can't I...
2015年12月17日 下午9:46，"Mingye Wang" <notifications@github.com>写道：

**Comment by Arthur2e5** [comment]
Just make them the same. Already said that in comment 0.

**Comment by Arthur2e5** [comment]
Design failure is design failure. Remove it before people get used to it.

**Comment by MingcongBai** [comment]
Explain that a little further?
2015年12月17日 下午9:48，"Icenowy Zheng" <notifications@github.com>写道：

**Comment by MingcongBai** [comment]
I will agree with you on this point. Please proceed.
2015年12月17日 下午9:50，"Mingye Wang" <notifications@github.com>写道：

**Comment by Arthur2e5** [comment]
Too lazy to touch the code. All solutions are there, just apply them yourself.

I am wiping the OpenJDK butt.

**Comment by MingcongBai** [comment]
Alright, tomorrow morning.
2015年12月17日 下午9:57，"Mingye Wang" <notifications@github.com>写道：

**Comment by Arthur2e5** [comment]
?
